profile: private
region: us-east-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: cloudvision-trial
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_function.lambda_handler
  description: Cloud Vision API trial
  timeout: 10
  memory_size: 128
