key_id: {{ env['AWS_KMS_KEY_ID'] }}
cipher_texts:
  GOOGLE_API_KEY: CiC4xW9lg7HaxaueeN+d9yJMyY1uw1i7tYVvQz9I8+e2UBKvAQEBAgB4uMVvZYOx2sWrnnjfnfciTMmNbsNYu7WFb0M/SPPntlAAAACGMIGDBgkqhkiG9w0BBwagdjB0AgEAMG8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMFbfdC4DVWleT3RgAgEQgEIKWqK8K3LeSk/cu7ZtXqhGvayoVuW4KKw7oUjqA6LCOsU4/LlO4uDxj9y452e3mX+VWbXdRisF5LO7qE4/CyAFmOI=
